"""Add restaurant_user  model

Revision ID: 6d41eba96006
Revises: cdc8a03fb018
Create Date: 2024-05-21 20:29:56.964362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d41eba96006'
down_revision: Union[str, None] = 'cdc8a03fb018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
