"""Add Restaurant model

Revision ID: 7f9d9c600b07
Revises: 6af758771ccd
Create Date: 2024-05-21 20:24:16.045485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7f9d9c600b07"
down_revision: Union[str, None] = "6af758771ccd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "restaurants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("rate", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("restaurants")


# ### end Alembic commands ###
